# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |vagrant|
    vagrant.vm.box = "vetbase/centos-7"

    # always use vagrant's insecure key
    vagrant.ssh.insert_key = false

    # virtualbox specific settings
    vagrant.vm.provider "virtualbox" do |v|
        # custom name
        v.name = "vetbase-docker"

        # speed up docker builds
        v.customize ["modifyvm", :id, "--nictype1", "virtio"]
    end

    # run ansible playbook
    vagrant.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end
end
