---
- hosts: all
  become: true
  vars:
    update_packages: True
  tasks:
    - name: Update CentOS
      yum: name=* state=latest update_cache=yes

    - name: Install PostgreSQL 9.6 RPM
      yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm state=installed

    - name: Install PostgreSQL 9.6
      yum: name={{ item }} state=installed
      with_items:
        - postgresql96
        - postgresql96-server

    - name: Initiate database
      command: /usr/pgsql-9.6/bin/postgresql96-setup initdb

    - name: Start PostgreSQL and Enable
      service: name=postgresql-9.6 enabled=yes state=started

    #- name: Ensure PostgreSQL is listening on all localhost
    #  lineinfile: dest=/var/lib/pgsql/9.6/data/postgresql.conf
    #    regexp='^#?listen_addresses\s*='
    #    line="listen_addresses = '127.0.0.1'"
    #    state=present
    #  notify: restart postgresql

    #- lineinfile: dest=/var/lib/pgsql/9.6/data/pg_hba.conf
    #              regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
    #              line='host all all 127.0.0.1/32 md5'
    #              insertbefore=BOF
    #  notify: restart postgresql

#  handlers:
#    - name: restart postgresql
#      service: name=postgresql-9.6 state=restarted
