---
- hosts: all
  become: true
  vars:
    update_packages: True
  tasks:
    - name: Update CentOS
      yum: name=* state=latest update_cache=yes

    - name: Install PostgreSQL 9.6 RPM
      yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm state=installed

    - name: Install PostgreSQL 9.6
      yum: name=postgresql96-server state=latest
