# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

IP_ADDRESS = "192.168.27.54"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |vagrant|
    vagrant.vm.box = "vetbase/centos-7"

    # set IP address
    vagrant.vm.network "private_network", ip: IP_ADDRESS

    # always use vagrant's insecure key
    vagrant.ssh.insert_key = false

    # virtualbox specific settings
    vagrant.vm.provider "virtualbox" do |v|
        # custom name
        v.name = "vetbase-postgres-9.6"
    end

    # run ansible provisioner
    vagrant.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yml"
    end
end
