---
- hosts: all
  become: true
  tasks:
    - name: Add EPEL Repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    - name: Add Virtualbox Repository
      yum_repository:
        name: virtualbox
        description: VirtualBox Repo
        baseurl: http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo

    - name: Update CentOS
      yum: name=* state=latest update_cache=yes

    - name: Download minikube release
      get_url:
        url: https://storage.googleapis.com/minikube/releases/v0.12.2/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: u=rw,g=rx,o=rx

    - name: Install Docker
      shell: curl -sSL https://get.docker.com/ | sh

    - name: Start and Enable Docker
      service: name=docker state=started enabled=yes

    - name: Download Docker Compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.8.1/docker-compose-`uname -s`-`uname -m` > /usr/bin/docker-compose

    - name: Make Docker Compose Executable
      shell: chmod +x /usr/bin/docker-compose

    - name: Add vagrant user to docker group
      user: name='vagrant' groups=docker append=yes

    - name: Reboot Server
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
      become: false
