---
- hosts: all
  become: true
  tasks:
    - name: Update CentOS
      yum: name=* state=latest

    - name: Add EPEL Repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    - name: Install Golang
      yum: name=golang state=latest
      environment:
        GOROOT: /usr/lib/golang
        GOBIN: $GOROOT/bin
        GOPATH: /development
        PATH: $PATH:$GOROOT:$GOPATH
